version: 2
jobs:
  build:
    working_directory: ~/android-remote-stacktrace-logger
    docker:
      - image: bitriseio/android-ndk:v2018_04_21-09_12-b976
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Make gradle wrapper executable
          command: chmod +x gradlew
      - run:
          name: Debug
          command: ./gradlew assembleDebug
      - store_artifacts:
                path: app/build/outputs/apk
                destination: apk
      - run:
          name: Release
          command: ./gradlew assembleRelease
      - store_artifacts:
                path: app/build/outputs/apk
                destination: apk

